#!/usr/bin/env bash
set -uo pipefail

if [[ ! -v ITORIS_SESSION ]]; then
	echo "This script can only be run in an itoris session"
	exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $# -le 2 ]]; then
  echo "Usage: $0 <project-root> <bundle-path> [flags...]" >&2
  exit 1
fi

if [[ "$(cat /proc/sys/fs/inotify/max_user_instances)" -le 256 ]]; then
  echo "[warn]"
  echo "[warn] Max number of user instances on inotify is set to a small value"
  echo "[warn] For larger projects, this may result in hooks not working."
  echo "[warn] You may try increasing the value of /proc/sys/fs/inotify/max_user_instances"
  echo "[warn]"
fi

ROOT_PATH=$1
BUNDLE_PATH=$2

READ_HOOKS_DIR="$BUNDLE_PATH/calls/read"
SAVE_HOOKS_DIR="$BUNDLE_PATH/calls/save"
CREATE_HOOKS_DIR="$BUNDLE_PATH/calls/create"
DELETE_HOOKS_DIR="$BUNDLE_PATH/calls/delete"
MOVE_IN_HOOKS_DIR="$BUNDLE_PATH/calls/move-in"
MOVE_OUT_HOOKS_DIR="$BUNDLE_PATH/calls/move-out"

OPEN_HOOKS_DIR="$BUNDLE_PATH/calls/open"
CLOSE_HOOKS_DIR="$BUNDLE_PATH/calls/close"
MOVE_HOOKS_DIR="$BUNDLE_PATH/calls/move"
ADD_HOOKS_DIR="$BUNDLE_PATH/calls/add"
REMOVE_HOOKS_DIR="$BUNDLE_PATH/calls/remove"

FIRST_SAVE_HOOKS_DIR="$BUNDLE_PATH/calls/first-save-file"

if ! command -v inotifywait >/dev/null 2>&1; then
  echo "inotifywait not found. Install inotify-tools." >&2
  exit 1
fi

ROOT="$(cd "$1" 2>/dev/null && pwd)" || { echo "Not a directory: $1" >&2; exit 1; }

declare -A JUST_CREATED
PAUSED=false

run_hooks() {
  local hooks_dir="$1"

  if [[ ! -d "$hooks_dir" ]]; then
    return 1
  fi

  local project_root="$2"
  local changed_path="${3:-}"
  local hook

  [[ -d "$hooks_dir" ]] || return 0

  PAUSED=true

  while IFS= read -r -d '' hook; do
    if [[ -e "$hook" ]]; then
      echo "[hook] $(basename "$hooks_dir")/$(basename "$hook")  <-  $changed_path"
      PROJECT_ROOT="$project_root" CHANGED_FILE="$changed_path" "$hook" "$project_root" "$changed_path"
    else
      echo "[warn] broken symlink, skipping: $hook" >&2
    fi
  done < <(find "$hooks_dir" -maxdepth 1 \( -type f -o -type l \) -print0 | sort -z)

  # Drain any events inotify queued *while* hooks were running (they were
  # generated by the hooks themselves, or by real edits during that window)
  # before resuming. Non-blocking: only reads what's already buffered.
  while read -r -t 0.2 -u "${PIPE_FD}" _drain_line; do :; done 2>/dev/null

  PAUSED=false
  return 0
}

echo "Watching: $ROOT"
echo

EXCLUDE_REGEX='(^|/)(\.git|__pycache__|node_modules|\.venv|venv)(/|$)'

# Open the inotifywait stream on a named FD so we can drain it above.
exec {PIPE_FD}< <(inotifywait -m "${@:3}" \
  --exclude "$EXCLUDE_REGEX" \
  -e create -e close_write -e close_nowrite -e moved_to -e moved_from -e delete \
  --format '%w%f|%e' \
  "$ROOT")

while IFS='|' read -r -u "${PIPE_FD}" path events; do
  $PAUSED && continue

  IFS=',' read -ra event_list <<< "$events"

  for e in "${event_list[@]}"; do
    case "$e" in
      CREATE)
        JUST_CREATED["$path"]=1
        run_hooks "$CREATE_HOOKS_DIR" "$ROOT_PATH" "$path"
        run_hooks "$ADD_HOOKS_DIR" "$ROOT_PATH" "$path"
        ;;
      CLOSE_WRITE)
        if [[ -n "${JUST_CREATED[$path]:-}" ]]; then
          unset 'JUST_CREATED[$path]'
          run_hooks "$FIRST_SAVE_HOOKS_DIR" "$ROOT_PATH" "$path"
        else
          run_hooks "$SAVE_HOOKS_DIR" "$ROOT_PATH" "$path"
        fi
        run_hooks "$CLOSE_HOOKS_DIR" "$ROOT_PATH" "$path"
        ;;
      CLOSE_NOWRITE)
        run_hooks "$READ_HOOKS_DIR" "$ROOT_PATH" "$path"
        run_hooks "$CLOSE_HOOKS_DIR" "$ROOT_PATH" "$path"
        ;;
      DELETE)
        unset 'JUST_CREATED[$path]'
        run_hooks "$DELETE_HOOKS_DIR" "$ROOT_PATH" "$path"
        run_hooks "$REMOVE_HOOKS_DIR" "$ROOT_PATH" "$path"
        ;;
      MOVED_TO)
        JUST_CREATED["$path"]=1
        run_hooks "$MOVE_IN_HOOKS_DIR" "$ROOT_PATH" "$path"
        run_hooks "$MOVE_HOOKS_DIR" "$ROOT_PATH" "$path"
        run_hooks "$ADD_HOOKS_DIR" "$ROOT_PATH" "$path"
        ;;
      MOVED_FROM)
        unset 'JUST_CREATED[$path]'
        run_hooks "$MOVE_OUT_HOOKS_DIR" "$ROOT_PATH" "$path"
        run_hooks "$MOVE_HOOKS_DIR" "$ROOT_PATH" "$path"
        run_hooks "$REMOVE_HOOKS_DIR" "$ROOT_PATH" "$path"
        ;;
    esac
  done
done
